Added some functions for the latest quote price display
ayang726/Project-2 pull request #43
Opened 2019-07-07 13:30 UTC by mariarabin

1) home.handlebars - Updated the id
2) data.js - added the function updatingLatestPrice
3) apiRoutes.js - added the latestPrice api route
4) dataFetch.js - listed dataFetchManager.getLatestPrice function
5) iexInterface.js - added the latestPrice function

2019-07-07 14:32 UTC, alexjzyang requested changes

2019-07-07 14:32 UTC, ayang726 commented on controller/iexInterface.js
> +iexRequest.test.latestPrice = () => { return axios.get(iexRequest.parseTestUrl("stock/aapl/quote/latestPrice")); }
could you please merge with master then correct the way iexRequest is written please?
Thanks!

2019-07-07 14:32 UTC, ayang726 commented on public/js/data.js
> +        latestPrice.append(response);
since you have a priceChart, do you mind adding this function to priceChart? Because data.js is getting crowded
Thanks!

2019-07-11 00:52 UTC, mariarabin commented
to delete as this will be replaced by https://github.com/ayang726/Project-2/pull/54

2019-07-11 00:52 UTC, closed without merging